### PR TITLE
add composer.json

### PR DESCRIPTION
**Pull request by bragento**
add composer.json for installation with composer

### CODE REVIEW

**Comment by wigman** [comment]
Thanks!

**Comment by bragento** [comment]
That was fast ;)

Could you also make a new relase for that change? Then we are able to use your Repository instead of our fork

**Comment by wigman** [comment]
Ofcourse, I just created a 0.4.3 release.

**Comment by bragento** [comment]
nice, thanks

**Comment by virani06** [comment]
how can i change the addtional carousal image size beacuse after selecting the swatch color addition color image size will be the 75_75 so how can i change it my default size is different than the 100_125

**Comment by wigman** [comment]
Hello Virani. It sounds like you are not using the default theme, it's hard to explain where to look without knowing your theme.. Maybe you can email me a demo url so I can have a look.

**Comment by virani06** [comment]
yes i able to do in js file but one question it is posiible to use slider of my theme in that file so if more image than it is disply in carousel slider

**Comment by wigman** [comment]
You could, but it would require some custom coding. I can't tell if you'd be able to do it yourself since I don't know how much knowledge you have about programming:)

**Pull request merged**
