### PR TITLE
Added compatibility withy Amasty Stockstatus

### PR DESCRIPTION
**Pull request by avra911**

### CODE REVIEW

**Comment by wigman** [comment]
Hi Avra,

Thanks for contributing. I'm a bit hesitant about accepting patches to specific third-party extensions, partly because I can't test it. Also this could potentially get really messy if we end up including every possible conflicting extension.

Sorry, and thanks again.
Willem

**Comment by avra911** [comment]
Hi, Wigman!

Thanks for your feedback!

From your explanations, it means `OrganicInternet_SimpleConfigurableProducts` is your module?

Best,
Razvan

PS: it should not affect any of your functionality, I see no reason why to reject my PR, you gave no choice than using a different fork which will accept to work with the rest of magento community out there

**Comment by avra911** [comment]
cc @wigman

**Comment by avra911** [comment]
danke!

**Comment by wigman** [comment]
It means that that I am using, and therefore was able to test, OrganicInternet_SimpleConfigurableProducts. I don't own Amasty Stockstatus.

I'd prefer to test changes before accepting pull requests.

**Comment by avra911** [comment]
Now I understood, one was an opensource and one was paid module.

Have a nice day!

Thanks,
Razvan

**Comment by wigman** [comment]
Exactly:) You're welcome, and thanks in return!

**Pull request merged**
